FROM ubuntu

RUN apt-get update -y
RUN ap-get install -y openjdk-8-jdk wget 

WORKDIR /opt
RUN wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.88/bin/apache-tomcat-9.0.88.tar.gz
RUN tar -xvzf  apache-tomcat-9.0.88.tar.gz
RUN mv apache-tomcat-9.0.88 tomcat

COPY target/welcomeapp.war /tomcat/webapps/

EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh", "run"]